### ISSUE TITLE
unable to run transcoding example file 

### ISSUE THREAD

**Issue by lalamax3d** [jonghwanhyeon/python-ffmpeg#1]
Hi,
thanks for sharing project, seems very interesting, i am on python 3.6.8 and seems to get installed via pip correctly. but this line
from ffmpeg import FFmpeg was giving error.
i thought it might be conflicting with ffmpeg-python library also installed, i tried removing that one and still wasn't working..
 so i copy main ffmpeg directory in root folder and line started working. that fixed basic import error. to test further, i put example transcoding file in main directly and running it. giving me following error (log) .. Any ideas..

(konstruct) C:\Users\lalat\Documents\Dev\konstruct>python transcoding.py
```
arguments: ['ffmpeg', '-y', '-i', 'input.mp4', '-c:v', 'libx264', '-vf', 'scale=1280:-1', '-preset', 'veryslow', '-crf', '24', 'ouptut.mp4']
Traceback (most recent call last):
  File "transcoding.py", line 42, in <module>                                            loop.run_until_complete(ffmpeg.execute())
  File "C:\Users\lalat\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 484, in run_until_complete                                                    return future.result()
  File "C:\Users\lalat\Documents\Dev\konstruct\ffmpeg\ffmpeg.py", line 72, in execute                                                                                         stderr=asyncio.subprocess.PIPE,
  File "C:\Users\lalat\AppData\Local\Programs\Python\Python36\lib\asyncio\subprocess.py", line 225, in create_subprocess_exec                                                 stderr=stderr, **kwds)
  File "C:\Users\lalat\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 1211, in subprocess_exec                                                      bufsize, **kwargs)
  File "C:\Users\lalat\AppData\Local\Programs\Python\Python36\lib\asyncio\coroutines.py", line 212, in coro
    res = func(*args, **kw)
  File "C:\Users\lalat\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 360, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
```

**Comment by jonghwanhyeon** [comment]
Hello,

On Windows, the default `asyncio` event loop does not support `subprocess`. You should set the default event loop as `ProactorEventLoop`.

Please refer to this document: https://docs.python.org/3/library/asyncio-platforms.html#asyncio-windows-subprocess

**Comment by lalamax3d** [comment]
thanks, will surely check soon.
