### ISSUE TITLE
Error while import

### ISSUE THREAD

**Issue by mi4code** [jonghwanhyeon/python-ffmpeg#19]
I upgraded to the latest version (2.0.1) and I am getting following error when importing.

```python
>>> from ffmpeg import FFmpeg

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Me\AppData\Local\Programs\Python\Python38\lib\site-packages\ffmpeg\__init__.py", line 1, in <module>
    from .ffmpeg import FFmpeg, FFmpegError
  File "C:\Users\Me\AppData\Local\Programs\Python\Python38\lib\site-packages\ffmpeg\ffmpeg.py", line 13, in <module>
    from ffmpeg import types
  File "C:\Users\Me\AppData\Local\Programs\Python\Python38\lib\site-packages\ffmpeg\types.py", line 10, in <module>
    Option = Union[Iterable[T], T]
TypeError: 'ABCMeta' object is not subscriptable

>>>
```

Am I just doing something wrong or is it a bug?

**Comment by jonghwanhyeon** [comment]
Fixed in version 2.0.2. Thanks for your report!
