### ISSUE TITLE
Question: How to extract subtitle with stdout?

### ISSUE THREAD

**Issue by moi15moi** [jonghwanhyeon/python-ffmpeg#30]
I saw this example: https://github.com/jonghwanhyeon/python-ffmpeg/blob/main/examples/output-as-bytes-via-stdout.py

I am currently trying to extract the subtitle with stdout:
```py
from pathlib import Path
from ffmpeg import FFmpeg, Progress


def main():
    video_path = Path("C:\\XXX\\video.mkv")

    ffmpeg = (
        FFmpeg()
        .input(video_path)
        .output(
            "pipe:1",
            map=["0:4"],
        )
    )

    subtitles = ffmpeg.execute()

if __name__ == "__main__":
    main()
```

But, I received this exception:
```py
Traceback (most recent call last):
  File "c:\Users\Admin\Desktop\test.py", line 21, in <module>
    main()
  File "c:\Users\Admin\Desktop\test.py", line 18, in main
    subtitles = ffmpeg.execute()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\ffmpeg\ffmpeg.py", line 150, in execute
    raise FFmpegError(f"Non-zero exit status {self._process.returncode}")
ffmpeg.ffmpeg.FFmpegError: Non-zero exit status 1
```

What can I do to avoid this exception and be able to extract the subtitle into the stdout?

**Comment by jonghwanhyeon** [comment]
If possible, could you share a clip of the input video?

**Comment by moi15moi** [comment]
Sure, here is the video: https://drive.google.com/file/d/1ISJMOGSW9iHOgBaunOLBNezMqpWHWnQy/view?usp=sharing

**Comment by moi15moi** [comment]
Oh, I just realised I needed to write the extention.

```py
from pathlib import Path
from ffmpeg import FFmpeg, Progress


def main():
    video_path = Path("C:\\XXX\\video.mkv")

    ffmpeg = (
        FFmpeg()
        .input(video_path)
        .output(
            "pipe:1.ass",
            map=["0:4"],
        )
    )

    subtitles = ffmpeg.execute()

if __name__ == "__main__":
    main()
```

**Comment by moi15moi** [comment]
I would have another question.
How can we use multiple output with pipe?

Currently, it merge the 2 pipe.
```py
from ffmpeg import FFmpeg

def main():
    video_path = "video.mkv"

    ffmpeg = (
        FFmpeg()
        .input(video_path)
        .output(
            "pipe:4.ass",
            map=["0:4"],
        )
        .output(
            "pipe:5.ass",
            map=["0:5"],
        )

    )

    subtitles = ffmpeg.execute()

    print(subtitles)

if __name__ == "__main__":
    main()
```

**Comment by jonghwanhyeon** [comment]
I am so sorry but currently `python-ffmpeg` only supports `stdout` which is `pipe:1`. I think you can detour this by executing `ffmpeg` multiple times.

**Comment by moi15moi** [comment]
> I think you can detour this by executing `ffmpeg` multiple times.

Sure, but I guess in term of performance, it is a bit faster to extract multiple subtitle in one call than call ffmpeg to extract 1 track at the time.
