### ISSUE TITLE
Key error on progress

### ISSUE THREAD

**Issue by nathanaelneveux** [jonghwanhyeon/python-ffmpeg#4]
I haven't been getting any progress events firing since I started testing and using this package a few days ago - since it wasn't needed for my particular app I haven't looked into it but while debugging something else I got this trace back.

```
Task exception was never retrieved
future: <Task finished coro=<FFmpeg._read_stderr() done, defined at /usr/local/python3.6/lib/python3.6/site-packages/ffmpeg/ffmpeg.py:109> exception=KeyError('bitrate',)>
Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/site-packages/ffmpeg/ffmpeg.py", line 111, in _read_stderr
    self.emit('stderr', line.decode('utf-8'))
  File "/usr/local/python3.6/lib/python3.6/site-packages/pyee/_base.py", line 108, in emit
    handled = self._call_handlers(event, args, kwargs)
  File "/usr/local/python3.6/lib/python3.6/site-packages/pyee/_base.py", line 91, in _call_handlers
    self._emit_run(f, args, kwargs)
  File "/usr/local/python3.6/lib/python3.6/site-packages/pyee/_compat.py", line 49, in _emit_run
    coro = f(*args, **kwargs)
  File "/usr/local/python3.6/lib/python3.6/site-packages/ffmpeg/ffmpeg.py", line 114, in _on_stderr
    progress = parse_progress(line)
  File "/usr/local/python3.6/lib/python3.6/site-packages/ffmpeg/utils.py", line 56, in parse_progress
    if items['bitrate'] == 'N/A':
KeyError: 'bitrate'
```
running code like this
```
ffmpeg = FFmpeg().option(
        're'
    ).input(
        cg['STREAM_INPUT_PATH']
    ).output(
        rtmp_output_address,
        codec='copy',
        bufsize=cg['BUFFER_SIZE'],
        f='flv',
    )

@ffmpeg.on('progress')
    def on_progress(progress):
        print(progress)

loop = asyncio.get_event_loop()
    loop.run_until_complete(ffmpeg.execute())
    loop.close()
```
other than not getting any progress events everything seems to work including other event types

python-ffmpeg = "^1.0.9"
Python Version 3.6.3
FFmpeg version 4.2.2
testing on a mac 10.15.3 and deployed on a centos 6 server v86.0.13

**Comment by jonghwanhyeon** [comment]
Hello!
Thank you for reporting the bug and I fixed this issue in version 1.0.11 😃
